config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :companies
  resources :contacts
  resources :messages
  resources :psychologists
  resources :users
  # resources :package_clients
  # resources :package_psychologists
  resources :package_types
  resources :packages do
    member do
      get 'checkout'
    end
  end

  # TODO: fix constraints to accept only requests from pagseguro
  # pagseguro, at least in sandbox, uses different ip's per request, not the specified below
  # ws.pagseguro.uol.com.br || sandbox.pagseguro.uol.com.br
  # constraints(host: 'ws.pagseguro.uol.com.br') do
  post 'package_payments' => 'package_payments#create', as: 'payment_notification'
  # end

  resources :interviews do
    collection do
      get 'calendar'
      get 'schedule'
      patch 'schedule_update/:id' => 'interviews#schedule_update', as: 'schedule_update'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: 'u'

  get 'panel(/index)' => 'panels#index', as: 'panel_index'

  root to: 'home#index'
end

app/models/package_client.rb
class PackageClient < ApplicationRecord
  belongs_to :client
  belongs_to :package

  validates :package, presence: true
  validates :client, presence: true, uniqueness: { scope: :package }
end

app/controllers/package_clients_controller.rb
class PackageClientsController < ApplicationController
  before_action :set_package_client, only: [:show, :edit, :update, :destroy]

  # GET /package_clients
  # GET /package_clients.json
  def index
    @package_clients = policy_scope(PackageClient)
  end

  # GET /package_clients/1
  # GET /package_clients/1.json
  def show
  end

  # GET /package_clients/new
  def new
    @package_client = PackageClient.new
    authorize @package_client
  end

  # GET /package_clients/1/edit
  def edit
  end

  # POST /package_clients
  # POST /package_clients.json
  def create
    @package_client = PackageClient.new(package_client_params)
    authorize @package_client

    respond_to do |format|
      if @package_client.save
        format.html { redirect_to @package_client, notice: 'PackageClient was successfully created.' }
        format.json { render :show, status: :created, location: @package_client }
      else
        format.html { render :new }
        format.json { render json: @package_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_clients/1
  # PATCH/PUT /package_clients/1.json
  def update
    respond_to do |format|
      if @package_client.update(package_client_params)
        format.html { redirect_to @package_client, notice: 'PackageClient was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_client }
      else
        format.html { render :edit }
        format.json { render json: @package_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_clients/1
  # DELETE /package_clients/1.json
  def destroy
    @package_client.destroy
    respond_to do |format|
      format.html { redirect_to package_clients_url, notice: 'PackageClient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_client
      @package_client = PackageClient.find(params[:id])
      authorize @package_client
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_client_params
      params.require(:package_client).permit(:client_id)
    end
end

app/helpers/package_clients_helper.rb
module PackageClientsHelper
end

app/views/package_clients/_form.html.erb
<%= form_for(package_client) do |f| %>
  <% if package_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(package_client.errors.count, "error") %> prohibited this package_client from being saved:</h2>

      <ul>
      <% package_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %>
    <%= f.text_field :client_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_clients/edit.html.erb
<h1>Editing PackageClient</h1>

<%= render 'form', package_client: @package_client %>

<%= link_to 'Show', @package_client %> |
<%= link_to 'Back', package_clients_path %>

app/views/package_clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PackageClients</h1>

<table>
  <thead>
    <tr>
      <th> Client ID </th>
      <th> Package ID </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @package_clients.each do |package_client| %>
      <tr>
        <td><%= package_client.client_id %></td>
        <td><%= package_client.package_id %></td>
        <td><%= link_to 'Show', package_client %></td>
        <td><%= link_to 'Edit', edit_package_client_path(package_client) %></td>
        <td><%= link_to 'Destroy', package_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New PackageClient', new_package_client_path %>

app/views/package_clients/new.html.erb
<h1>New PackageClient</h1>

<%= render 'form', package_client: @package_client %>

<%= link_to 'Back', package_clients_path %>

app/views/package_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @package_client.client %>
</p>

<%= link_to 'Edit', edit_package_client_path(@package_client) %> |
<%= link_to 'Back', package_clients_path %>