config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :companies
  resources :contacts
  resources :messages
  resources :psychologists
  resources :users
  # resources :package_clients
  # resources :package_psychologists
  resources :package_types
  resources :packages do
    member do
      get 'checkout'
    end
  end

  # TODO: fix constraints to accept only requests from pagseguro
  # pagseguro, at least in sandbox, uses different ip's per request, not the specified below
  # ws.pagseguro.uol.com.br || sandbox.pagseguro.uol.com.br
  # constraints(host: 'ws.pagseguro.uol.com.br') do
  post 'package_payments' => 'package_payments#create', as: 'payment_notification'
  # end

  resources :interviews do
    collection do
      get 'calendar'
      get 'schedule'
      patch 'schedule_update/:id' => 'interviews#schedule_update', as: 'schedule_update'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: 'u'

  get 'panel(/index)' => 'panels#index', as: 'panel_index'

  root to: 'home#index'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :packages

  validates :user, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_action :verify_user_kind_existence, only: [:new, :create]
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @q = policy_scope(Company).ransack(params[:q])
    @companies = @q.result(distinct: true)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user = current_user
    authorize @company

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
      authorize @company
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :agent, :cnpj, :user_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => "form-horizontal company" } do |f| %>

  <% if @company.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :agent, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :agent, :class => 'form-control' %>
    </div>
    <%=f.error_span(:agent) %>
  </div>
  <div class="form-group">
    <%= f.label :cnpj, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cnpj, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cnpj) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Cadastrar", :class => 'btn btn-primary' %>
      
    </div>
  </div>

<% end %>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= search_form_for @q do |f| %>

  <%= f.search_field :name_cont, placeholder: "Nome" %>

  <%= f.submit "Procurar" %>

<% end %>

<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:agent) %></th>
      <th><%= model_class.human_attribute_name(:cnpj) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.id, company_path(company) %></td>
        <td><%= company.name %></td>
        <% user_company = User.find_by_id(company.user_id) %>
        <td><%= user_company.email %></td>
        <td><%= company.agent %></td>
        <td><%= company.cnpj %></td>
        <td><%=l company.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      company_path(company), :class => 'btn btn-default btn-xs' %>
          <% if policy(company).edit? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_company_path(company), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if policy(@companies).create? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Novo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <% user_company = User.find_by_id(@company.user_id) %>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= user_company.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:agent) %>:</strong></dt>
  <dd><%= @company.agent %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cnpj) %>:</strong></dt>
  <dd><%= @company.cnpj %></dd>
 
</dl>

<% if current_user.administrator? %>
	<%= link_to t('.back', :default => t("helpers.links.back")),
	              companies_path, :class => 'btn btn-default'  %>
<% else %>
	<%= link_to t('.back', :default => t("helpers.links.back")),
	              panel_index_path, :class => 'btn btn-default'  %>
<% end %>