config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :companies
  resources :contacts
  resources :messages
  resources :psychologists
  resources :users
  # resources :package_clients
  # resources :package_psychologists
  resources :package_types
  resources :packages do
    member do
      get 'checkout'
    end
  end

  # TODO: fix constraints to accept only requests from pagseguro
  # pagseguro, at least in sandbox, uses different ip's per request, not the specified below
  # ws.pagseguro.uol.com.br || sandbox.pagseguro.uol.com.br
  # constraints(host: 'ws.pagseguro.uol.com.br') do
  post 'package_payments' => 'package_payments#create', as: 'payment_notification'
  # end

  resources :interviews do
    collection do
      get 'calendar'
      get 'schedule'
      patch 'schedule_update/:id' => 'interviews#schedule_update', as: 'schedule_update'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: 'u'

  get 'panel(/index)' => 'panels#index', as: 'panel_index'

  root to: 'home#index'
end

app/models/package_psychologist.rb
class PackagePsychologist < ApplicationRecord
  belongs_to :psychologist
  belongs_to :package

  validates :package, presence: true
  validates :psychologist, presence: true, uniqueness: { scope: :package }
end

app/controllers/package_psychologists_controller.rb
class PackagePsychologistsController < ApplicationController
  before_action :set_package_psychologist, only: [:show, :edit, :update, :destroy]

  # GET /package_psychologists
  # GET /package_psychologists.json
  def index
    @package_psychologists = policy_scope(PackagePsychologist)
  end

  # GET /package_psychologists/1
  # GET /package_psychologists/1.json
  def show
  end

  # GET /package_psychologists/new
  def new
    @package_psychologist = PackagePsychologist.new
    authorize @package_psychologist
  end

  # GET /package_psychologists/1/edit
  def edit
  end

  # POST /package_psychologists
  # POST /package_psychologists.json
  def create
    @package_psychologist = PackagePsychologist.new(package_psychologist_params)
    authorize @package_psychologists

    respond_to do |format|
      if @package_psychologist.save
        format.html { redirect_to @package_psychologist, notice: 'PackagePsychologist was successfully created.' }
        format.json { render :show, status: :created, location: @package_psychologist }
      else
        format.html { render :new }
        format.json { render json: @package_psychologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_psychologists/1
  # PATCH/PUT /package_psychologists/1.json
  def update
    respond_to do |format|
      if @package_psychologist.update(package_psychologist_params)
        format.html { redirect_to @package_psychologist, notice: 'PackagePsychologist was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_psychologist }
      else
        format.html { render :edit }
        format.json { render json: @package_psychologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_psychologists/1
  # DELETE /package_psychologists/1.json
  def destroy
    @package_psychologist.destroy
    respond_to do |format|
      format.html { redirect_to package_psychologists_url, notice: 'PackagePsychologist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_psychologist
      @package_psychologist = PackagePsychologist.find(params[:id])
      authorize @package_psychologist
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_psychologist_params
      params.require(:package_psychologist).permit(:psychologist_id)
    end
end

app/helpers/package_psychologists_helper.rb
module PackagePsychologistsHelper
end

app/views/package_psychologists/_form.html.erb
<%= form_for(package_psychologist) do |f| %>
  <% if package_psychologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(package_psychologist.errors.count, "error") %> prohibited this package_psychologist from being saved:</h2>

      <ul>
      <% package_psychologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :psychologist_id %>
    <%= f.text_field :psychologist_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/package_psychologists/edit.html.erb
<h1>Editing PackagePsychologist</h1>

<%= render 'form', package_psychologist: @package_psychologist %>

<%= link_to 'Show', @package_psychologist %> |
<%= link_to 'Back', package_psychologists_path %>

app/views/package_psychologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PackagePsychologists</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Psychologist Name</th>
      <th>Package ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @package_psychologists.each do |package_psychologist| %>
      <tr>
        <td><%= package_psychologist.id %></td>
        <td><%= package_psychologist.psychologist.name %></td>
        <td><%= package_psychologist.package_id %></td>
        <td><%= link_to 'Show', package_psychologist %></td>
        <td><%= link_to 'Edit', edit_package_psychologist_path(package_psychologist) %></td>
        <td><%= link_to 'Destroy', package_psychologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New PackagePsychologist', new_package_psychologist_path %>

app/views/package_psychologists/new.html.erb
<h1>New PackagePsychologist</h1>

<%= render 'form', package_psychologist: @package_psychologist %>

<%= link_to 'Back', package_psychologists_path %>

app/views/package_psychologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Psychologist:</strong>
  <%= @package_psychologist.psychologist %>
</p>

<%= link_to 'Edit', edit_package_psychologist_path(@package_psychologist) %> |
<%= link_to 'Back', package_psychologists_path %>