config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :companies
  resources :contacts
  resources :messages
  resources :psychologists
  resources :users
  # resources :package_clients
  # resources :package_psychologists
  resources :package_types
  resources :packages do
    member do
      get 'checkout'
    end
  end

  # TODO: fix constraints to accept only requests from pagseguro
  # pagseguro, at least in sandbox, uses different ip's per request, not the specified below
  # ws.pagseguro.uol.com.br || sandbox.pagseguro.uol.com.br
  # constraints(host: 'ws.pagseguro.uol.com.br') do
  post 'package_payments' => 'package_payments#create', as: 'payment_notification'
  # end

  resources :interviews do
    collection do
      get 'calendar'
      get 'schedule'
      patch 'schedule_update/:id' => 'interviews#schedule_update', as: 'schedule_update'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: 'u'

  get 'panel(/index)' => 'panels#index', as: 'panel_index'

  root to: 'home#index'
end

app/controllers/package_types_controller.rb
class PackageTypesController < ApplicationController
  before_action :set_package_type, only: [:show, :edit, :update, :destroy]

  # GET /package_types
  # GET /package_types.json
  def index
    @package_types = policy_scope(PackageType).all
  end

  # GET /package_types/1
  # GET /package_types/1.json
  def show
  end

  # GET /package_types/new
  def new
    @package_type = PackageType.new
    authorize @package_type
  end

  # GET /package_types/1/edit
  def edit
  end

  # POST /package_types
  # POST /package_types.json
  def create
    @package_type = PackageType.new(package_type_params)
    authorize @package_type

    respond_to do |format|
      if @package_type.save
        format.html { redirect_to @package_type, notice: 'Tipo package was successfully created.' }
        format.json { render :show, status: :created, location: @package_type }
      else
        format.html { render :new }
        format.json { render json: @package_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /package_types/1
  # PATCH/PUT /package_types/1.json
  def update
    respond_to do |format|
      if @package_type.update(package_type_params)
        format.html { redirect_to @package_type, notice: 'Tipo package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package_type }
      else
        format.html { render :edit }
        format.json { render json: @package_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_types/1
  # DELETE /package_types/1.json
  def destroy
    @package_type.destroy
    respond_to do |format|
      format.html { redirect_to package_types_url, notice: 'Tipo package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package_type
      @package_type = PackageType.find(params[:id])
      authorize @package_type
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_type_params
      params.require(:package_type).permit(:name, :interview_counter, :price)
    end
end

app/helpers/package_types_helper.rb
module PackageTypesHelper
end

app/views/package_types/_form.html.erb
<%= form_for @package_type, :html => { :class => "form-horizontal package_type" } do |f| %>

  <% if @package_type.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@package_type.errors.count, "error") %> prohibited this package_type from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @package_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :interview_counter, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :interview_counter, :class => 'form-control' %>
    </div>
    <%=f.error_span(:interview_counter) %>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <div class="input-group">
        <div class="input-group-addon">R$</div>
        <%= f.text_field :price, :class => 'form-control' %>
        <div class="input-group-addon">,00</div>
      </div>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Cadastrar", :class => 'btn btn-primary' %>
    </div>

  </div>

<% end %>

app/views/package_types/edit.html.erb
<%- model_class = PackageType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/package_types/index.html.erb
<%- model_class = PackageType -%>
<div class="page-header">
  <h1>Tipos de Pacote</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:interview_counter) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @package_types.each do |package_type| %>
      <tr>
        <td><%= link_to package_type.id, package_type_path(package_type) %></td>
        <td><%= package_type.name %></td>
        <td><%= package_type.interview_counter %></td>
        <td><%=l package_type.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      package_type_path(package_type), :class => 'btn btn-default btn-xs' %>
          <% if policy(package_type).edit? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_package_type_path(package_type), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      package_type_path(package_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if policy(@package_types).create? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_package_type_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/package_types/new.html.erb
<h1>New Tipo Package</h1>

<%= render 'form', package_type: @package_type %>

app/views/package_types/show.html.erb
<%- model_class = PackageType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @package_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:interview_counter) %>:</strong></dt>
  <dd><%= @package_type.interview_counter %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= number_to_currency(@package_type.price, unit: "R$", separator: ",", delimiter: ".") %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              package_types_path, :class => 'btn btn-default'  %>